/**
 * Datos de ubicaciones de Galicia - FincAirbnb
 * 
 * Lista completa de provincias y municipios de Galicia
 * para usar en formularios de selección
 * 
 * Datos extraídos de la tabla oficial de equivalencias de ferrados
 */

export interface LocationData {
  provincia: string;
  municipio: string;
}

// Provincias de Galicia
export const PROVINCIAS_GALICIA = [
  { value: 'a_coruna', label: 'A Coruña' },
  { value: 'lugo', label: 'Lugo' },
  { value: 'ourense', label: 'Ourense' },
  { value: 'pontevedra', label: 'Pontevedra' }
];

// Municipios por provincia - Lista completa extraída de la tabla oficial
export const MUNICIPIOS_BY_PROVINCIA: Record<string, Array<{value: string, label: string}>> = {
  'a_coruna': [
    { value: 'abadin', label: 'Abadín' },
    { value: 'abegondo', label: 'Abegondo' },
    { value: 'ames', label: 'Ames' },
    { value: 'amoeiro', label: 'Amoeiro' },
    { value: 'aranga', label: 'Aranga' },
    { value: 'arbo', label: 'Arbo' },
    { value: 'ares', label: 'Ares' },
    { value: 'a_arnoa', label: 'A Arnóa' },
    { value: 'arteixo', label: 'Arteixo' },
    { value: 'arzua', label: 'Arzúa' },
    { value: 'avion', label: 'Avión' },
    { value: 'baiona', label: 'Baiona' },
    { value: 'baleira', label: 'Baleira' },
    { value: 'baltar', label: 'Baltar' },
    { value: 'bande', label: 'Bande' },
    { value: 'a_bana', label: 'A Baña' },
    { value: 'banos_de_molgas', label: 'Baños de Molgas' },
    { value: 'baralla', label: 'Baralla' },
    { value: 'barbadas', label: 'Barbadás' },
    { value: 'o_barco_de_valdeorras', label: 'O Barco de Valdeorras' },
    { value: 'barreiros', label: 'Barreiros' },
    { value: 'barro', label: 'Barro' },
    { value: 'beade', label: 'Beade' },
    { value: 'beariz', label: 'Beariz' },
    { value: 'becerrea', label: 'Becerreá' },
    { value: 'begonte', label: 'Begonte' },
    { value: 'bergondo', label: 'Bergondo' },
    { value: 'betanzos', label: 'Betanzos' },
    { value: 'os_blancos', label: 'Os Blancos' },
    { value: 'boboras', label: 'Boborás' },
    { value: 'boimorto', label: 'Boimorto' },
    { value: 'boiro', label: 'Boiro' },
    { value: 'a_bola', label: 'A Bola' },
    { value: 'o_bolo', label: 'O Bolo' },
    { value: 'boqueixon', label: 'Boqueixón' },
    { value: 'boveda', label: 'Bóveda' },
    { value: 'brion', label: 'Brión' },
    { value: 'bueu', label: 'Bueu' },
    { value: 'burela', label: 'Burela' },
    { value: 'cabana_de_bergantinos', label: 'Cabana de Bergantiños' },
    { value: 'cabanas', label: 'Cabanas' },
    { value: 'caldas_de_reis', label: 'Caldas de Reis' },
    { value: 'calvos_de_randin', label: 'Calvos de Randín' },
    { value: 'camarinhas', label: 'Camariñas' },
    { value: 'cambados', label: 'Cambados' },
    { value: 'cambre', label: 'Cambre' },
    { value: 'campo_lameiro', label: 'Campo Lameiro' },
    { value: 'cangas', label: 'Cangas' },
    { value: 'a_caniza', label: 'A Cañiza' },
    { value: 'a_capela', label: 'A Capela' },
    { value: 'carballeda_de_avia', label: 'Carballeda de Avia' },
    { value: 'carballeda_de_valdeorras', label: 'Carballeda de Valdeorras' },
    { value: 'carballedo', label: 'Carballedo' },
    { value: 'o_carballino', label: 'O Carballiño' },
    { value: 'carballo', label: 'Carballo' },
    { value: 'carino', label: 'Cariño' },
    { value: 'carnota', label: 'Carnota' },
    { value: 'carral', label: 'Carral' },
    { value: 'cartelle', label: 'Cartelle' },
    { value: 'castrelo_de_mino', label: 'Castrelo de Miño' },
    { value: 'castrelo_do_val', label: 'Castrelo do Val' },
    { value: 'castro_caldelas', label: 'Castro Caldelas' },
    { value: 'castro_de_rei', label: 'Castro de Rei' },
    { value: 'castroverde', label: 'Castroverde' },
    { value: 'catoira', label: 'Catoira' },
    { value: 'cedeira', label: 'Cedeira' },
    { value: 'cee', label: 'Cee' },
    { value: 'celanova', label: 'Celanova' },
    { value: 'cenlle', label: 'Cenlle' },
    { value: 'cerceda', label: 'Cerceda' },
    { value: 'cerdedo_cotobade', label: 'Cerdedo-Cotobade' },
    { value: 'cerdido', label: 'Cerdido' },
    { value: 'cervantes', label: 'Cervantes' },
    { value: 'cervo', label: 'Cervo' },
    { value: 'chandrexa_de_queixa', label: 'Chandrexa de Queixa' },
    { value: 'chantada', label: 'Chantada' },
    { value: 'coiros', label: 'Coirós' },
    { value: 'coles', label: 'Coles' },
    { value: 'corcubion', label: 'Corcubión' },
    { value: 'o_corgo', label: 'O Corgo' },
    { value: 'coristanco', label: 'Coristanco' },
    { value: 'cortegada', label: 'Cortegada' },
    { value: 'a_coruna', label: 'A Coruña' },
    { value: 'cospeito', label: 'Cospeito' },
    { value: 'covelo', label: 'Covelo' },
    { value: 'crecente', label: 'Crecente' },
    { value: 'cualedro', label: 'Cualedro' },
    { value: 'culleredo', label: 'Culleredo' },
    { value: 'cuntis', label: 'Cuntis' },
    { value: 'curtis', label: 'Curtis' },
    { value: 'dodro', label: 'Dodro' },
    { value: 'dozon', label: 'Dozón' },
    { value: 'dumbria', label: 'Dumbría' },
    { value: 'entrimo', label: 'Entrimo' },
    { value: 'esgos', label: 'Esgos' },
    { value: 'a_estrada', label: 'A Estrada' },
    { value: 'fene', label: 'Fene' },
    { value: 'ferrol', label: 'Ferrol' },
    { value: 'fisterra', label: 'Fisterra' },
    { value: 'folgoso_do_courel', label: 'Folgoso do Courel' },
    { value: 'a_fonsagrada', label: 'A Fonsagrada' },
    { value: 'forcarei', label: 'Forcarei' },
    { value: 'fornelos_de_montes', label: 'Fornelos de Montes' },
    { value: 'foz', label: 'Foz' },
    { value: 'frades', label: 'Frades' },
    { value: 'friol', label: 'Friol' },
    { value: 'gomesende', label: 'Gomesende' },
    { value: 'gondomar', label: 'Gondomar' },
    { value: 'o_grove', label: 'O Grove' },
    { value: 'a_guarda', label: 'A Guarda' },
    { value: 'a_gudina', label: 'A Gudiña' },
    { value: 'guitiriz', label: 'Guitiriz' },
    { value: 'guntin', label: 'Guntín' },
    { value: 'a_illa_de_arousa', label: 'A Illa de Arousa' },
    { value: 'o_incio', label: 'O Incio' },
    { value: 'o_irixo', label: 'O Irixo' },
    { value: 'irixoa', label: 'Irixoa' },
    { value: 'lalin', label: 'Lalín' },
    { value: 'a_lama', label: 'A Lama' },
    { value: 'lancara', label: 'Láncara' },
    { value: 'a_laracha', label: 'A Laracha' },
    { value: 'larouco', label: 'Larouco' },
    { value: 'laxe', label: 'Laxe' },
    { value: 'laza', label: 'Laza' },
    { value: 'leiro', label: 'Leiro' },
    { value: 'lobeira', label: 'Lobeira' },
    { value: 'lobios', label: 'Lobios' },
    { value: 'lourenza', label: 'Lourenzá' },
    { value: 'lousame', label: 'Lousame' },
    { value: 'lugo', label: 'Lugo' },
    { value: 'maceda', label: 'Maceda' },
    { value: 'malpica_de_bergantinos', label: 'Malpica de Bergantiños' },
    { value: 'manzaneda', label: 'Manzaneda' },
    { value: 'manon', label: 'Mañón' },
    { value: 'marin', label: 'Marín' },
    { value: 'maside', label: 'Maside' },
    { value: 'mazaricos', label: 'Mazaricos' },
    { value: 'meano', label: 'Meaño' },
    { value: 'meira', label: 'Meira' },
    { value: 'meis', label: 'Meis' },
    { value: 'melide', label: 'Melide' },
    { value: 'melon', label: 'Melón' },
    { value: 'a_merca', label: 'A Merca' },
    { value: 'mesia', label: 'Mesía' },
    { value: 'a_mezquita', label: 'A Mezquita' },
    { value: 'mino', label: 'Miño' },
    { value: 'moana', label: 'Moaña' },
    { value: 'moeche', label: 'Moeche' },
    { value: 'mondariz', label: 'Mondariz' },
    { value: 'mondariz_balneario', label: 'Mondariz-Balneario' },
    { value: 'mondonedo', label: 'Mondoñedo' },
    { value: 'monfero', label: 'Monfero' },
    { value: 'monforte_de_lemos', label: 'Monforte de Lemos' },
    { value: 'montederramo', label: 'Montederramo' },
    { value: 'monterrei', label: 'Monterrei' },
    { value: 'monterroso', label: 'Monterroso' },
    { value: 'morana', label: 'Morana' },
    { value: 'mos', label: 'Mos' },
    { value: 'mugardos', label: 'Mugardos' },
    { value: 'muras', label: 'Muras' },
    { value: 'muros', label: 'Muros' },
    { value: 'muxia', label: 'Muxía' },
    { value: 'naron', label: 'Narón' },
    { value: 'navia_de_suarna', label: 'Navia de Suarna' },
    { value: 'neda', label: 'Neda' },
    { value: 'negueira_de_muniz', label: 'Negueira de Muñiz' },
    { value: 'negreira', label: 'Negreira' },
    { value: 'as_neves', label: 'As Neves' },
    { value: 'nigran', label: 'Nigrán' },
    { value: 'as_nogais', label: 'As Nogais' },
    { value: 'noia', label: 'Noia' },
    { value: 'oia', label: 'Oia' },
    { value: 'oleiros', label: 'Oleiros' },
    { value: 'ordes', label: 'Ordes' },
    { value: 'oroso', label: 'Oroso' },
    { value: 'ortigueira', label: 'Ortigueira' },
    { value: 'ourense', label: 'Ourense' },
    { value: 'ourol', label: 'Ourol' },
    { value: 'outeiro_de_rei', label: 'Outeiro de Rei' },
    { value: 'outes', label: 'Outes' },
    { value: 'paderne', label: 'Paderne' },
    { value: 'paderne_de_allariz', label: 'Paderne de Allariz' },
    { value: 'padrenda', label: 'Padrenda' },
    { value: 'padron', label: 'Padrón' },
    { value: 'palas_de_rei', label: 'Palas de Rei' },
    { value: 'panton', label: 'Pantón' },
    { value: 'paradea', label: 'Paradela' },
    { value: 'o_paramo', label: 'O Páramo' },
    { value: 'a_pastoriza', label: 'A Pastoriza' },
    { value: 'pazos_de_borben', label: 'Pazos de Borbén' },
    { value: 'pedrafita_do_cebreiro', label: 'Pedrafita do Cebreiro' },
    { value: 'pereiro_de_aguiar', label: 'Pereiro de Aguiar' },
    { value: 'a_peroxa', label: 'A Peroxa' },
    { value: 'o_pino', label: 'O Pino' },
    { value: 'pinor', label: 'Piñor' },
    { value: 'a_pobra_de_trives', label: 'A Pobra de Trives' },
    { value: 'a_pobra_do_brollon', label: 'A Pobra do Brollón' },
    { value: 'a_pobra_do_caraminal', label: 'A Pobra do Caramiñal' },
    { value: 'poio', label: 'Poio' },
    { value: 'pol', label: 'Pol' },
    { value: 'ponteareas', label: 'Ponteareas' },
    { value: 'ponte_caldelas', label: 'Ponte Caldelas' },
    { value: 'ponteceso', label: 'Ponteceso' },
    { value: 'pontecesures', label: 'Pontecesures' },
    { value: 'pontedeume', label: 'Pontedeume' },
    { value: 'a_pontenova', label: 'A Pontenova' },
    { value: 'pontes_de_garcia_rodriguez', label: 'Pontes de García Rodríguez' },
    { value: 'pontevedra', label: 'Pontevedra' },
    { value: 'o_porrino', label: 'O Porriño' },
    { value: 'portas', label: 'Portas' },
    { value: 'porto_do_son', label: 'Porto do Son' },
    { value: 'portomarin', label: 'Portomarín' },
    { value: 'punxin', label: 'Punxín' },
    { value: 'quintela_de_leirado', label: 'Quintela de Leirado' },
    { value: 'quiroga', label: 'Quiroga' },
    { value: 'rabade', label: 'Rábade' },
    { value: 'rairiz_de_veiga', label: 'Rairiz de Veiga' },
    { value: 'ramiras', label: 'Ramirás' },
    { value: 'redondela', label: 'Redondela' },
    { value: 'ribadavia', label: 'Ribadavia' },
    { value: 'ribadeo', label: 'Ribadeo' },
    { value: 'ribadumia', label: 'Ribadumia' },
    { value: 'ribas_de_sil', label: 'Ribas de Sil' },
    { value: 'ribeira', label: 'Ribeira' },
    { value: 'ribeira_de_piquin', label: 'Ribeira de Piquín' },
    { value: 'rios', label: 'Riós' },
    { value: 'rianxo', label: 'Rianxo' },
    { value: 'riotorto', label: 'Riotorto' },
    { value: 'rodeiro', label: 'Rodeiro' },
    { value: 'o_rosal', label: 'O Rosal' },
    { value: 'rois', label: 'Rois' },
    { value: 'a_rua', label: 'A Rúa' },
    { value: 'rubia', label: 'Rubiá' },
    { value: 'sada', label: 'Sada' },
    { value: 'salceda_de_caselas', label: 'Salceda de Caselas' },
    { value: 'salvaterra_de_mino', label: 'Salvaterra de Miño' },
    { value: 'samos', label: 'Samos' },
    { value: 'san_amaro', label: 'San Amaro' },
    { value: 'san_cibrao_das_vinas', label: 'San Cibrao das Viñas' },
    { value: 'san_cristovo_de_cea', label: 'San Cristovo de Cea' },
    { value: 'san_sadurnino', label: 'San Sadurniño' },
    { value: 'san_xoan_de_rio', label: 'San Xoán de Río' },
    { value: 'sandias', label: 'Sandías' },
    { value: 'santa_comba', label: 'Santa Comba' },
    { value: 'santiago_de_compostela', label: 'Santiago de Compostela' },
    { value: 'santiso', label: 'Santiso' },
    { value: 'sanxenxo', label: 'Sanxenxo' },
    { value: 'sarreaus', label: 'Sarreaus' },
    { value: 'sarria', label: 'Sarria' },
    { value: 'o_savinao', label: 'O Saviñao' },
    { value: 'silleda', label: 'Silleda' },
    { value: 'sober', label: 'Sober' },
    { value: 'sobrado', label: 'Sobrado' },
    { value: 'as_somozas', label: 'As Somozas' },
    { value: 'soutomaior', label: 'Soutomaior' },
    { value: 'taboada', label: 'Taboada' },
    { value: 'taboadela', label: 'Taboadela' },
    { value: 'teo', label: 'Teo' },
    { value: 'toen', label: 'Toén' },
    { value: 'tomino', label: 'Tomiño' },
    { value: 'toques', label: 'Toques' },
    { value: 'tordoia', label: 'Tordoia' },
    { value: 'touro', label: 'Touro' },
    { value: 'trabada', label: 'Trabada' },
    { value: 'trasmiras', label: 'Trasmiras' },
    { value: 'trazo', label: 'Trazo' },
    { value: 'triacastela', label: 'Triacastela' },
    { value: 'tui', label: 'Tui' },
    { value: 'o_valadouro', label: 'O Valadouro' },
    { value: 'valdovino', label: 'Valdoviño' },
    { value: 'valga', label: 'Valga' },
    { value: 'vedra', label: 'Vedra' },
    { value: 'a_veiga', label: 'A Veiga' },
    { value: 'verea', label: 'Verea' },
    { value: 'verin', label: 'Verín' },
    { value: 'viana_do_bolo', label: 'Viana do Bolo' },
    { value: 'o_vicedo', label: 'O Vicedo' },
    { value: 'vigo', label: 'Vigo' },
    { value: 'vilaboa', label: 'Vilaboa' },
    { value: 'vilagarcia_de_arousa', label: 'Vilagarcía de Arousa' },
    { value: 'vilalba', label: 'Vilalba' },
    { value: 'vilamarin', label: 'Vilamarín' },
    { value: 'vilamartin_de_valdeorras', label: 'Vilamartín de Valdeorras' },
    { value: 'vilanova_de_arousa', label: 'Vilanova de Arousa' },
    { value: 'vilar_de_barrio', label: 'Vilar de Barrio' },
    { value: 'vilar_de_santos', label: 'Vilar de Santos' },
    { value: 'vilardevos', label: 'Vilardevós' },
    { value: 'vilariño_de_conso', label: 'Vilariño de Conso' },
    { value: 'vilasantar', label: 'Vilasantar' },
    { value: 'vimianzo', label: 'Vimianzo' },
    { value: 'viveiro', label: 'Viveiro' },
    { value: 'xermade', label: 'Xermade' },
    { value: 'xinzo_de_limia', label: 'Xinzo de Limia' },
    { value: 'xove', label: 'Xove' },
    { value: 'xunqueira_de_ambia', label: 'Xunqueira de Ambía' },
    { value: 'xunqueira_de_espadanedo', label: 'Xunqueira de Espadanedo' },
    { value: 'zas', label: 'Zas' }
  ],
  'lugo': [
    { value: 'abadin', label: 'Abadín' },
    { value: 'alfoz', label: 'Alfoz' },
    { value: 'antas_de_ulla', label: 'Antas de Ulla' },
    { value: 'baleira', label: 'Baleira' },
    { value: 'baralla', label: 'Baralla' },
    { value: 'barreiros', label: 'Barreiros' },
    { value: 'becerrea', label: 'Becerreá' },
    { value: 'begonte', label: 'Begonte' },
    { value: 'boveda', label: 'Bóveda' },
    { value: 'carballedo', label: 'Carballedo' },
    { value: 'castro_de_rei', label: 'Castro de Rei' },
    { value: 'castroverde', label: 'Castroverde' },
    { value: 'cervantes', label: 'Cervantes' },
    { value: 'cervo', label: 'Cervo' },
    { value: 'o_corgo', label: 'O Corgo' },
    { value: 'cospeito', label: 'Cospeito' },
    { value: 'chantada', label: 'Chantada' },
    { value: 'folgoso_do_courel', label: 'Folgoso do Courel' },
    { value: 'a_fonsagrada', label: 'A Fonsagrada' },
    { value: 'foz', label: 'Foz' },
    { value: 'friol', label: 'Friol' },
    { value: 'guntin', label: 'Guntín' },
    { value: 'guitiriz', label: 'Guitiriz' },
    { value: 'o_incio', label: 'O Incio' },
    { value: 'lancara', label: 'Láncara' },
    { value: 'lourenza', label: 'Lourenzá' },
    { value: 'lugo', label: 'Lugo' },
    { value: 'mantas', label: 'Mantas' },
    { value: 'meira', label: 'Meira' },
    { value: 'mondonedo', label: 'Mondoñedo' },
    { value: 'monforte_de_lemos', label: 'Monforte de Lemos' },
    { value: 'monterroso', label: 'Monterroso' },
    { value: 'muras', label: 'Muras' },
    { value: 'navia_de_suarna', label: 'Navia de Suarna' },
    { value: 'negueira_de_muniz', label: 'Negueira de Muñiz' },
    { value: 'as_nogais', label: 'As Nogais' },
    { value: 'ourol', label: 'Ourol' },
    { value: 'outeiro_de_rei', label: 'Outeiro de Rei' },
    { value: 'palas_de_rei', label: 'Palas de Rei' },
    { value: 'panton', label: 'Pantón' },
    { value: 'paradea', label: 'Paradela' },
    { value: 'o_paramo', label: 'O Páramo' },
    { value: 'a_pastoriza', label: 'A Pastoriza' },
    { value: 'pedrafita_do_cebreiro', label: 'Pedrafita do Cebreiro' },
    { value: 'a_pobra_do_brollon', label: 'A Pobra do Brollón' },
    { value: 'pol', label: 'Pol' },
    { value: 'a_pontenova', label: 'A Pontenova' },
    { value: 'portomarin', label: 'Portomarín' },
    { value: 'quiroga', label: 'Quiroga' },
    { value: 'rabade', label: 'Rábade' },
    { value: 'ribadeo', label: 'Ribadeo' },
    { value: 'ribas_de_sil', label: 'Ribas de Sil' },
    { value: 'ribeira_de_piquin', label: 'Ribeira de Piquín' },
    { value: 'riotorto', label: 'Riotorto' },
    { value: 'samos', label: 'Samos' },
    { value: 'sarria', label: 'Sarria' },
    { value: 'o_savinao', label: 'O Saviñao' },
    { value: 'sober', label: 'Sober' },
    { value: 'taboada', label: 'Taboada' },
    { value: 'trabada', label: 'Trabada' },
    { value: 'triacastela', label: 'Triacastela' },
    { value: 'o_valadouro', label: 'O Valadouro' },
    { value: 'valdovino', label: 'Valdoviño' },
    { value: 'vilalba', label: 'Vilalba' },
    { value: 'viveiro', label: 'Viveiro' },
    { value: 'xermade', label: 'Xermade' },
    { value: 'xove', label: 'Xove' }
  ],
  'ourense': [
    { value: 'allariz', label: 'Allariz' },
    { value: 'amoeiro', label: 'Amoeiro' },
    { value: 'avion', label: 'Avión' },
    { value: 'a_arnoa', label: 'A Arnóa' },
    { value: 'baltar', label: 'Baltar' },
    { value: 'bande', label: 'Bande' },
    { value: 'banos_de_molgas', label: 'Baños de Molgas' },
    { value: 'barbadas', label: 'Barbadás' },
    { value: 'o_barco_de_valdeorras', label: 'O Barco de Valdeorras' },
    { value: 'barro', label: 'Barro' },
    { value: 'beade', label: 'Beade' },
    { value: 'beariz', label: 'Beariz' },
    { value: 'os_blancos', label: 'Os Blancos' },
    { value: 'boboras', label: 'Boborás' },
    { value: 'a_bola', label: 'A Bola' },
    { value: 'o_bolo', label: 'O Bolo' },
    { value: 'caldas_de_reis', label: 'Caldas de Reis' },
    { value: 'calvos_de_randin', label: 'Calvos de Randín' },
    { value: 'cambados', label: 'Cambados' },
    { value: 'carballeda_de_avia', label: 'Carballeda de Avia' },
    { value: 'carballeda_de_valdeorras', label: 'Carballeda de Valdeorras' },
    { value: 'carballedo', label: 'Carballedo' },
    { value: 'o_carballino', label: 'O Carballiño' },
    { value: 'cartelle', label: 'Cartelle' },
    { value: 'castrelo_de_mino', label: 'Castrelo de Miño' },
    { value: 'castrelo_do_val', label: 'Castrelo do Val' },
    { value: 'castro_caldelas', label: 'Castro Caldelas' },
    { value: 'celanova', label: 'Celanova' },
    { value: 'cenlle', label: 'Cenlle' },
    { value: 'chandrexa_de_queixa', label: 'Chandrexa de Queixa' },
    { value: 'coles', label: 'Coles' },
    { value: 'cortegada', label: 'Cortegada' },
    { value: 'cualedro', label: 'Cualedro' },
    { value: 'entrimo', label: 'Entrimo' },
    { value: 'esgos', label: 'Esgos' },
    { value: 'a_estrada', label: 'A Estrada' },
    { value: 'gomesende', label: 'Gomesende' },
    { value: 'gondomar', label: 'Gondomar' },
    { value: 'o_grove', label: 'O Grove' },
    { value: 'a_guarda', label: 'A Guarda' },
    { value: 'a_gudina', label: 'A Gudiña' },
    { value: 'o_irixo', label: 'O Irixo' },
    { value: 'lalin', label: 'Lalín' },
    { value: 'a_lama', label: 'A Lama' },
    { value: 'larouco', label: 'Larouco' },
    { value: 'laza', label: 'Laza' },
    { value: 'leiro', label: 'Leiro' },
    { value: 'lobeira', label: 'Lobeira' },
    { value: 'lobios', label: 'Lobios' },
    { value: 'maceda', label: 'Maceda' },
    { value: 'manzaneda', label: 'Manzaneda' },
    { value: 'marin', label: 'Marín' },
    { value: 'maside', label: 'Maside' },
    { value: 'meano', label: 'Meaño' },
    { value: 'melon', label: 'Melón' },
    { value: 'a_merca', label: 'A Merca' },
    { value: 'a_mezquita', label: 'A Mezquita' },
    { value: 'moana', label: 'Moaña' },
    { value: 'mondariz', label: 'Mondariz' },
    { value: 'mondariz_balneario', label: 'Mondariz-Balneario' },
    { value: 'montederramo', label: 'Montederramo' },
    { value: 'monterrei', label: 'Monterrei' },
    { value: 'ourense', label: 'Ourense' },
    { value: 'paderne_de_allariz', label: 'Paderne de Allariz' },
    { value: 'padrenda', label: 'Padrenda' },
    { value: 'pereiro_de_aguiar', label: 'Pereiro de Aguiar' },
    { value: 'a_peroxa', label: 'A Peroxa' },
    { value: 'pinor', label: 'Piñor' },
    { value: 'a_pobra_de_trives', label: 'A Pobra de Trives' },
    { value: 'a_pobra_do_brollon', label: 'A Pobra do Brollón' },
    { value: 'poio', label: 'Poio' },
    { value: 'punxin', label: 'Punxín' },
    { value: 'quintela_de_leirado', label: 'Quintela de Leirado' },
    { value: 'quiroga', label: 'Quiroga' },
    { value: 'rabade', label: 'Rábade' },
    { value: 'rairiz_de_veiga', label: 'Rairiz de Veiga' },
    { value: 'ramiras', label: 'Ramirás' },
    { value: 'redondela', label: 'Redondela' },
    { value: 'ribadavia', label: 'Ribadavia' },
    { value: 'ribadeo', label: 'Ribadeo' },
    { value: 'ribadumia', label: 'Ribadumia' },
    { value: 'ribas_de_sil', label: 'Ribas de Sil' },
    { value: 'rios', label: 'Riós' },
    { value: 'riotorto', label: 'Riotorto' },
    { value: 'rodeiro', label: 'Rodeiro' },
    { value: 'a_rua', label: 'A Rúa' },
    { value: 'rubia', label: 'Rubiá' },
    { value: 'san_amaro', label: 'San Amaro' },
    { value: 'san_cibrao_das_vinas', label: 'San Cibrao das Viñas' },
    { value: 'san_cristovo_de_cea', label: 'San Cristovo de Cea' },
    { value: 'san_xoan_de_rio', label: 'San Xoán de Río' },
    { value: 'sandias', label: 'Sandías' },
    { value: 'sarreaus', label: 'Sarreaus' },
    { value: 'sarria', label: 'Sarria' },
    { value: 'o_savinao', label: 'O Saviñao' },
    { value: 'silleda', label: 'Silleda' },
    { value: 'sober', label: 'Sober' },
    { value: 'soutomaior', label: 'Soutomaior' },
    { value: 'taboada', label: 'Taboada' },
    { value: 'taboadela', label: 'Taboadela' },
    { value: 'toen', label: 'Toén' },
    { value: 'tomino', label: 'Tomiño' },
    { value: 'trasmiras', label: 'Trasmiras' },
    { value: 'trazo', label: 'Trazo' },
    { value: 'tui', label: 'Tui' },
    { value: 'valga', label: 'Valga' },
    { value: 'a_veiga', label: 'A Veiga' },
    { value: 'verea', label: 'Verea' },
    { value: 'verin', label: 'Verín' },
    { value: 'viana_do_bolo', label: 'Viana do Bolo' },
    { value: 'vilamartin_de_valdeorras', label: 'Vilamartín de Valdeorras' },
    { value: 'vilamarin', label: 'Vilamarín' },
    { value: 'vilanova_de_arousa', label: 'Vilanova de Arousa' },
    { value: 'vilar_de_barrio', label: 'Vilar de Barrio' },
    { value: 'vilar_de_santos', label: 'Vilar de Santos' },
    { value: 'vilardevos', label: 'Vilardevós' },
    { value: 'vilariño_de_conso', label: 'Vilariño de Conso' },
    { value: 'xunqueira_de_ambia', label: 'Xunqueira de Ambía' },
    { value: 'xunqueira_de_espadanedo', label: 'Xunqueira de Espadanedo' }
  ],
  'pontevedra': [
    { value: 'agolada', label: 'Agolada' },
    { value: 'arbo', label: 'Arbo' },
    { value: 'baiona', label: 'Baiona' },
    { value: 'barro', label: 'Barro' },
    { value: 'caldas_de_reis', label: 'Caldas de Reis' },
    { value: 'cambados', label: 'Cambados' },
    { value: 'campo_lameiro', label: 'Campo Lameiro' },
    { value: 'cangas', label: 'Cangas' },
    { value: 'a_caniza', label: 'A Cañiza' },
    { value: 'catoira', label: 'Catoira' },
    { value: 'cerdedo_cotobade', label: 'Cerdedo-Cotobade' },
    { value: 'cuntis', label: 'Cuntis' },
    { value: 'dozon', label: 'Dozón' },
    { value: 'a_estrada', label: 'A Estrada' },
    { value: 'forcarei', label: 'Forcarei' },
    { value: 'fornelos_de_montes', label: 'Fornelos de Montes' },
    { value: 'gondomar', label: 'Gondomar' },
    { value: 'o_grove', label: 'O Grove' },
    { value: 'a_guarda', label: 'A Guarda' },
    { value: 'a_illa_de_arousa', label: 'A Illa de Arousa' },
    { value: 'lalin', label: 'Lalín' },
    { value: 'a_lama', label: 'A Lama' },
    { value: 'marin', label: 'Marín' },
    { value: 'meano', label: 'Meaño' },
    { value: 'meis', label: 'Meis' },
    { value: 'moana', label: 'Moaña' },
    { value: 'mondariz', label: 'Mondariz' },
    { value: 'mondariz_balneario', label: 'Mondariz-Balneario' },
    { value: 'morana', label: 'Morana' },
    { value: 'mos', label: 'Mos' },
    { value: 'as_neves', label: 'As Neves' },
    { value: 'nigran', label: 'Nigrán' },
    { value: 'oia', label: 'Oia' },
    { value: 'poio', label: 'Poio' },
    { value: 'ponteareas', label: 'Ponteareas' },
    { value: 'ponte_caldelas', label: 'Ponte Caldelas' },
    { value: 'pontecesures', label: 'Pontecesures' },
    { value: 'pontevedra', label: 'Pontevedra' },
    { value: 'o_porrino', label: 'O Porriño' },
    { value: 'portas', label: 'Portas' },
    { value: 'redondela', label: 'Redondela' },
    { value: 'ribadumia', label: 'Ribadumia' },
    { value: 'rodeiro', label: 'Rodeiro' },
    { value: 'o_rosal', label: 'O Rosal' },
    { value: 'rois', label: 'Rois' },
    { value: 'salceda_de_caselas', label: 'Salceda de Caselas' },
    { value: 'salvaterra_de_mino', label: 'Salvaterra de Miño' },
    { value: 'silleda', label: 'Silleda' },
    { value: 'sober', label: 'Sober' },
    { value: 'soutomaior', label: 'Soutomaior' },
    { value: 'taboada', label: 'Taboada' },
    { value: 'taboadela', label: 'Taboadela' },
    { value: 'teo', label: 'Teo' },
    { value: 'tomino', label: 'Tomiño' },
    { value: 'tui', label: 'Tui' },
    { value: 'valga', label: 'Valga' },
    { value: 'vigo', label: 'Vigo' },
    { value: 'vilaboa', label: 'Vilaboa' },
    { value: 'vilagarcia_de_arousa', label: 'Vilagarcía de Arousa' },
    { value: 'vilanova_de_arousa', label: 'Vilanova de Arousa' }
  ]
};

/**
 * Obtiene los municipios de una provincia específica
 */
export function getMunicipiosByProvincia(provinciaValue: string): Array<{value: string, label: string}> {
  return MUNICIPIOS_BY_PROVINCIA[provinciaValue] || [];
}

/**
 * Obtiene el nombre completo de una provincia por su valor
 */
export function getProvinciaLabel(provinciaValue: string): string {
  const provincia = PROVINCIAS_GALICIA.find(p => p.value === provinciaValue);
  return provincia ? provincia.label : provinciaValue;
}

/**
 * Obtiene el nombre completo de un municipio por su valor y provincia
 */
export function getMunicipioLabel(municipioValue: string, provinciaValue: string): string {
  const municipios = MUNICIPIOS_BY_PROVINCIA[provinciaValue];
  if (!municipios) return municipioValue;
  
  const municipio = municipios.find(m => m.value === municipioValue);
  return municipio ? municipio.label : municipioValue;
}